#lang ivy1.8

type pid = {0..3}

relation link(X:pid, Y:pid)
invariant [symmetric_link] link(X, Y) -> link(Y, X)

process host(p: pid) = {
    after init {
        link(X,Y) := false;
    }

    export action connect(y:pid) = {
        link(p, y) := true;
        link(y, p) := true;
    }

    export action disconnect(y:pid) = {
        if link(p, y) {
            link(p, y) := false;
            #link(y, p) := false;
        }
    }
}
