#lang ivy1.8

include numbers

process mutator = {
    type t
    interpret t -> int

    export action inc
    export action dec

    var count : t

    import action show(c: t)

    after init {
        count := 1;
    }

    implement inc {
        count := count + 1;
        show(count)
    }
    implement dec {
        count := count - 1;
        show(count)
    }

    specification {
        after inc {
            assert true
        }
    }

    invariant [nonnegativity] count >= 0
}

attribute method=bmc[10]
